import {
  PlannerSnapshot,
  SummaryDay,
  PlacesToEatRecord,
  PlacesToVisitRecord,
} from "./types";

const summaryDays: SummaryDay[] = [
  {
    date: "2026-07-24",
    points: [
      {
        pointId: "p-1",
        text: "Arrive at Bandaranaike Airport and transfer to Negombo.",
        originalTime: "08:30",
        estimatedDurationMinutes: 120,
        suggestedStartTime: "08:45",
        suggestedEndTime: "10:45",
        sourceActivityId: "a-1",
      },
      {
        pointId: "p-2",
        text: "Check in and refresh before heading to the lagoon walk.",
        originalTime: "11:15",
        estimatedDurationMinutes: 90,
        suggestedStartTime: "11:30",
        suggestedEndTime: "13:00",
        sourceActivityId: "a-2",
      },
      {
        pointId: "p-3",
        text: "Visit Negombo Fish Market for local seafood and photos.",
        originalTime: "13:15",
        estimatedDurationMinutes: 75,
        suggestedStartTime: "13:30",
        suggestedEndTime: "14:45",
        sourceActivityId: "a-3",
      },
      {
        pointId: "p-4",
        text: "Sunset at Negombo Beach with a short cafe break.",
        originalTime: "17:00",
        estimatedDurationMinutes: 105,
        suggestedStartTime: "16:50",
        suggestedEndTime: "18:35",
        sourceActivityId: "a-4",
      },
      {
        pointId: "p-5",
        text: "Dinner near Dutch Fort and prep for next-day road trip.",
        originalTime: "19:15",
        estimatedDurationMinutes: 95,
        suggestedStartTime: "19:00",
        suggestedEndTime: "20:35",
        sourceActivityId: "a-5",
      },
    ],
  },
  {
    date: "2026-07-25",
    points: [
      {
        pointId: "p-6",
        text: "Drive to Sigiriya and break at a highway tea point.",
        originalTime: "07:00",
        estimatedDurationMinutes: 240,
        suggestedStartTime: "07:15",
        suggestedEndTime: "11:15",
        sourceActivityId: "a-6",
      },
      {
        pointId: "p-7",
        text: "Climb Sigiriya Rock Fortress before the peak heat window.",
        originalTime: "11:30",
        estimatedDurationMinutes: 130,
        suggestedStartTime: "11:40",
        suggestedEndTime: "13:50",
        sourceActivityId: "a-7",
      },
      {
        pointId: "p-8",
        text: "Lunch and cool-down stop in central Dambulla.",
        originalTime: "14:10",
        estimatedDurationMinutes: 80,
        suggestedStartTime: "14:15",
        suggestedEndTime: "15:35",
        sourceActivityId: "a-8",
      },
      {
        pointId: "p-9",
        text: "Evening safari at Minneriya National Park.",
        originalTime: "16:00",
        estimatedDurationMinutes: 180,
        suggestedStartTime: "16:05",
        suggestedEndTime: "19:05",
        sourceActivityId: "a-9",
      },
      {
        pointId: "p-10",
        text: "Night market walk and early rest for next transfer.",
        originalTime: "20:00",
        estimatedDurationMinutes: 60,
        suggestedStartTime: "20:10",
        suggestedEndTime: "21:10",
        sourceActivityId: "a-10",
      },
    ],
  },
];

const placesToVisit: PlacesToVisitRecord[] = [
  {
    placeId: "v-1",
    itineraryId: "it-100",
    name: "Negombo Lagoon",
    addressText: "Hamilton Canal, Negombo",
    googleMapsUrl: "https://maps.google.com/?q=Negombo+Lagoon",
    category: "nature",
    sortOrder: 1,
  },
  {
    placeId: "v-2",
    itineraryId: "it-100",
    name: "Sigiriya Rock Fortress",
    addressText: "Sigiriya, Matale District",
    googleMapsUrl: "https://maps.google.com/?q=Sigiriya+Rock+Fortress",
    category: "attraction",
    sortOrder: 2,
  },
  {
    placeId: "v-3",
    itineraryId: "it-100",
    name: "Minneriya National Park",
    addressText: "Minneriya, North Central Province",
    googleMapsUrl: "https://maps.google.com/?q=Minneriya+National+Park",
    category: "nature",
    sortOrder: 3,
  },
];

const placesToEat: PlacesToEatRecord[] = [
  {
    placeId: "e-1",
    itineraryId: "it-100",
    name: "Sea Joy Restaurant",
    addressText: "Porutota Road, Negombo",
    googleMapsUrl: "https://maps.google.com/?q=Sea+Joy+Restaurant+Negombo",
    cuisineTags: ["seafood", "sri-lankan"],
    sortOrder: 1,
  },
  {
    placeId: "e-2",
    itineraryId: "it-100",
    name: "Pradeep Restaurant",
    addressText: "Inamaluwa Junction, Dambulla",
    googleMapsUrl: "https://maps.google.com/?q=Pradeep+Restaurant+Dambulla",
    cuisineTags: ["rice-and-curry", "local"],
    sortOrder: 2,
  },
  {
    placeId: "e-3",
    itineraryId: "it-100",
    name: "RastaRant",
    addressText: "Hotel Road, Sigiriya",
    googleMapsUrl: "https://maps.google.com/?q=RastaRant+Sigiriya",
    cuisineTags: ["fusion", "vegetarian"],
    sortOrder: 3,
  },
];

export const plannerSnapshotMock: PlannerSnapshot = {
  currentUser: {
    uid: "u-editor-1",
    email: "editor@tripplanner.local",
    displayName: "Aarav Sen",
    role: "editor",
  },
  itinerary: {
    itineraryId: "it-100",
    tripTitle: "Sri Lanka Discovery Loop",
    locationRegion: "Western + Cultural Triangle",
    startDate: "2026-07-24",
    endDate: "2026-07-25",
    status: "published",
    createdBy: "u-editor-1",
    updatedBy: "u-editor-1",
    days: [
      {
        date: "2026-07-24",
        notes: "Light day after flight arrival.",
        activities: [
          {
            activityId: "a-1",
            title: "Airport transfer",
            description: "Taxi to Negombo",
            originalStartTime: "08:30",
            originalDurationMinutes: 120,
            placeRefId: null,
            tags: ["transfer"],
          },
          {
            activityId: "a-2",
            title: "Hotel check-in",
            description: "Quick freshen-up",
            originalStartTime: "11:15",
            originalDurationMinutes: 90,
            placeRefId: null,
            tags: ["hotel"],
          },
          {
            activityId: "a-3",
            title: "Fish market",
            description: "Explore local scene",
            originalStartTime: "13:15",
            originalDurationMinutes: 75,
            placeRefId: "v-1",
            tags: ["market", "culture"],
          },
          {
            activityId: "a-4",
            title: "Beach sunset",
            description: "Walk and cafe",
            originalStartTime: "17:00",
            originalDurationMinutes: 105,
            placeRefId: "v-1",
            tags: ["beach"],
          },
          {
            activityId: "a-5",
            title: "Dinner",
            description: "Seafood dinner",
            originalStartTime: "19:15",
            originalDurationMinutes: 95,
            placeRefId: "e-1",
            tags: ["food"],
          },
        ],
      },
      {
        date: "2026-07-25",
        notes: "Early departure to avoid traffic.",
        activities: [
          {
            activityId: "a-6",
            title: "Drive to Sigiriya",
            description: "Road transfer with one break",
            originalStartTime: "07:00",
            originalDurationMinutes: 240,
            placeRefId: "v-2",
            tags: ["transfer"],
          },
          {
            activityId: "a-7",
            title: "Rock fortress",
            description: "Climb and viewpoints",
            originalStartTime: "11:30",
            originalDurationMinutes: 130,
            placeRefId: "v-2",
            tags: ["hiking", "history"],
          },
          {
            activityId: "a-8",
            title: "Lunch stop",
            description: "Dambulla town",
            originalStartTime: "14:10",
            originalDurationMinutes: 80,
            placeRefId: "e-2",
            tags: ["food"],
          },
          {
            activityId: "a-9",
            title: "Safari",
            description: "Minneriya park safari",
            originalStartTime: "16:00",
            originalDurationMinutes: 180,
            placeRefId: "v-3",
            tags: ["wildlife"],
          },
          {
            activityId: "a-10",
            title: "Night market",
            description: "Short local walk",
            originalStartTime: "20:00",
            originalDurationMinutes: 60,
            placeRefId: null,
            tags: ["leisure"],
          },
        ],
      },
    ],
  },
  summary: {
    summaryId: "sum-101",
    itineraryId: "it-100",
    version: 1,
    generatedBy: "u-editor-1",
    generatedAtIso: "2026-07-24T09:40:00.000Z",
    model: "gpt-5.3-codex-mock",
    status: "approved",
    highlights: [
      "Avoided peak heat for Sigiriya climb.",
      "Balanced transfer-heavy legs with slower evening slots.",
    ],
    warnings: ["Reserve safari tickets 24h before departure."],
    summaryDays,
  },
  placesToVisit,
  placesToEat,
};
